### ISSUE TITLE
micro:bit error if sensor not connected

### ISSUE THREAD

**Issue by microbit-giles** [bsiever/microbit-dstemp#1]
This extension is *awesome*!

One thing I noticed is that if you flash code made with it to a micro:bit that doesn't have a temperature sensor connected to the appropriate pin, I get a micro:bit 980 error. Would it be possible for the extension to trap that?

Thank you again for this, I've added a link to my blogpost at http://www.suppertime.co.uk/blogmywiki/2019/04/microbit-ds18b20-temperature-sensor/ 

best wishes
Giles

**Comment by bsiever** [comment]
Sorry I haven't replied sooner.  I'll try to look into it in the next week or two.

**Comment by microbit-giles** [comment]
No need to apologise and no hurry - thank you again for all your work on this.

**Comment by bsiever** [comment]
The new version (v0.1.14) seems to have fixed this.  Re-open / update if the problem persists or there are other side-effect.
